### ISSUE TITLE
so, how do I start a project? I want to try out some of my idea now! 

### ISSUE THREAD

**Issue by lymanlai** [open-company/projects#1]
I have already got some idea. I build them before for my own base on angularjs, restify, FlatUI.
now I want to try them on react, semantic-ui etc!

so, how do I start a project?

**Comment by open-company** [comment]
Please give me a little more time, I'll publish first batch of OCOSP soon.
As a starter, you can only **choose** a project to join, but not **publish** a very new project.

**Comment by wangyangjun** [comment]
@open-company  Hi, where can I find the projects? Are they not released yet?

**Comment by open-company** [comment]
Yes, they are not completely released yet.
I'm work on it these days.
